[workspace]
authors = ["Jeremy E Kozdon <jeremy@kozdon.net>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "prefix-sum"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "<1.0.0"
